sonar.projectKey=muskangill_8.2CDevSecOps
sonar.organization=muskangill
sonar.host.url=https://sonarcloud.io
sonar.login=${7dcca636113db9198cc1720b72f3b546211339ef}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
